### ISSUE TITLE
Make a minimal static website

### ISSUE THREAD

**Issue by fahadsultan** [fahadsultan/visualizing_dynamic_graphs#1]
Make a simple static HTML website with the following layouts: 

**Layout 1**: 
![Layout](https://i.stack.imgur.com/9jI6f.gif)

**Layout 2**: 
![Layout2](https://media.geeksforgeeks.org/wp-content/uploads/layout.png)

**Layout 3**: 
![Layout3](https://www.w3schools.com/html/img_sem_elements.gif)

---- 

Adding your name  to the header. 

Add three buttons in the menu section. 

Add a paragraph of text and an image in the content of the page. 

Add a short sentence in the footer. 

Make sure you are comfortable with layouts in HTML: using divs and relevant css properties.

**Comment by fahadsultan** [comment]
Ignore HTML forms, for now. 

Focus on divs, html ids and classes, styles.

**Comment by moultriedanger** [comment]
[SummerAssignment.zip](https://github.com/fahadsultan/visualizing_dynamic_graphs/files/11681816/SummerAssignment.zip)

**Comment by moultriedanger** [comment]
I just attached what ive been working on today on top of learning other concepts. Just a basic home page and then another page using layouts 2 and 3. Let me know if I implemented them correctly using the grid feature. And im still learning css so that could use a little work I know.

**Comment by fahadsultan** [comment]
@moultriedanger Looks good. Great job! 

I want you to do the following now: 

* Set opaque background colors for each section in the layouts.

You should finish up on the CSS bit and then move onto Javascript and EventHandlers. 

Using javascript, I want you to toggle between two different background images on every click of a link/button. 

We can talk this afternoon if you want.

**Comment by moultriedanger** [comment]
Thanks! I should have a good handle on things around 3 if you want to talk then.

**Comment by fahadsultan** [comment]
@moultriedanger 
1. Implement a dropdown in HTML that has numbers from 1 - 10. (Dropdowns are probably a part of HTML forms)
2. Add a button to your HTML page 
3. When the button is clicked, first read the selected number from the dropdown. Let's call the selected number x.
4. Add to a paragraph `<p></p>` in HTML numbers from 0 - x.

**Comment by fahadsultan** [comment]
Completed.
